apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
spec:
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
      - name: jaeger
        image: jaegertracing/jaeger:2.1.0
        env:
        - name: COLLECTOR_ZIPKIN_HOST_PORT
          value: ":9411"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        ports:
        - containerPort: 4317
        - containerPort: 4318
        - containerPort: 9411
        - containerPort: 14250
        - containerPort: 14268
        - containerPort: 16685
        - containerPort: 16686
        - containerPort: 5778
        - containerPort: 5779
        resources:
          requests:
            cpu: 200m
            memory: 180Mi
          limits:
            cpu: 300m
            memory: 300Mi
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  type: ClusterIP
  selector:
    app: jaeger
  ports:
  - name: "4317"
    port: 4317
    targetPort: 4317
  - name: "4318"
    port: 4318
    targetPort: 4318
  - name: "9411"
    port: 9411
    targetPort: 9411
  - name: "14250"
    port: 14250
    targetPort: 14250
  - name: "14268"
    port: 14268
    targetPort: 14268
  - name: "16685"
    port: 16685
    targetPort: 16685
  - name: "16686"
    port: 16686
    targetPort: 16686
  - name: "5778"
    port: 5778
    targetPort: 5778
  - name: "5779"
    port: 5779
    targetPort: 5779
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-frontend
spec:
  type: NodePort
  selector:
    app: jaeger
  ports:
  - name: "16686"
    port: 16686
    targetPort: 16686
  - name: "16685"
    port: 16685
    targetPort: 16685
