apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice
spec:
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      labels:
        app: userservice
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
        - name: server
          image: caiziqin/userservice:1.0.0  # 使用统一的镜像命名
          ports:
          - containerPort: 9555
          env:
          - name: PORT
            value: "9555"
          - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
            value: "http://jaeger:4317"
          - name: OTEL_RESOURCE_ATTRIBUTES 
            value: "service.name=userservice,service.version=1.0.0"
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          readinessProbe:
            initialDelaySeconds: 15
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:9555", "-rpc-timeout=5s"]
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 10
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:9555", "-rpc-timeout=5s"]
---
apiVersion: v1
kind: Service
metadata:
  name: userservice
spec:
  type: ClusterIP
  selector:
    app: userservice
  ports:
  - name: grpc
    port: 9555
    targetPort: 9555