apiVersion: v1
kind: Service
metadata:
  name: prometheus-frontend
  namespace: istio-system
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
  - name: "9090"
    port: 9090
    targetPort: 9090
    nodePort: 32601
---
apiVersion: v1
kind: Service
metadata:
  name: kiali-frontend
  namespace: istio-system
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: kiali
  ports:
  - name: "20001"
    port: 20001
    targetPort: 20001
    nodePort: 32602
